version: "3"

services:
    app:
      image: ban898/app:Gunicorn_And_Python
      ports:
        - "5000"

    nginx:
      image: ban898/app:Nginx
      depends_on:
        - app
      ports:
        - "80:8080"
        - "443:443"
