version: "3"

services:
    app:
      build:
        context: app
      image: ban898/app:Gunicorn_And_Python
      ports:
        - "5000"

    nginx:
      build:
        context: nginx
      image: ban898/app:Nginx
      volumes:
        - ./nginx/:/etc/nginx/:ro
      depends_on:
        - app
      ports:
        - "80:8080"
        - "443:443"
